Function naming conventions for services
DEFRA/water-abstraction-team pull request #82
Opened 2023-04-13 15:27 UTC by StuAA78

We have a couple of naming conventions relating to our use of services:
- Services generally have one exported function, named `go`
- The names of functions used internally in the service should start with an underscore

This PR documents these conventions.

2023-04-19 15:29 UTC, Cruikshanks requested changes
Thank you for taking the time to do this! Just one change I'd like to suggest.

2023-04-19 15:39 UTC, StuAA78 commented on coding_conventions.md
> +To this end, our convention is that services have a single exported function, called `go()`. Any functions used internally within the service should have a name starting with an underscore, to indica
Fair point! I've tweaked the wording now.

2023-04-19 15:43 UTC, Cruikshanks approved these changes
<img src="https://media2.giphy.com/media/a0Lgc1JvbfS4o/giphy.gif"/>

2023-04-20 16:05 UTC, Jozzey approved these changes
<img src="https://media2.giphy.com/media/qPcX2mzk3NmjC/giphy.gif"/>

2023-04-25 11:53 UTC, Beckyrose200 approved these changes
<img src="https://media2.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>
Looks good :)

2023-04-25 13:29 UTC, Jozzey approved these changes

2023-04-25 15:37 UTC, merged